using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Reflection;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace SkyVideoEditor {
    class Clip {
        public string Path; public string Name; public double Duration, Start, End; public int Width, Height; public double Fps;
        public double Length { get { return Math.Max(0, End - Start); } }
        public override string ToString() { return Name + "    " + Fmt(Start) + " → " + Fmt(End) + "    (" + Fmt(Length) + ")"; }
        public static string Fmt(double v) { v=Math.Max(0,v); int h=(int)(v/3600), m=(int)(v%3600/60); return string.Format(CultureInfo.InvariantCulture,"{0:00}:{1:00}:{2:00.000}",h,m,v%60); }
        public static double Parse(string text) {
            string[] p=text.Trim().Replace(',', '.').Split(':'); double x;
            if(p.Length==1) x=double.Parse(p[0],CultureInfo.InvariantCulture);
            else if(p.Length==2) x=double.Parse(p[0],CultureInfo.InvariantCulture)*60+double.Parse(p[1],CultureInfo.InvariantCulture);
            else if(p.Length==3) x=double.Parse(p[0],CultureInfo.InvariantCulture)*3600+double.Parse(p[1],CultureInfo.InvariantCulture)*60+double.Parse(p[2],CultureInfo.InvariantCulture);
            else throw new Exception("時間格式不正確");
            if(x<0) throw new Exception("時間不可小於 0"); return x;
        }
    }

    class MainForm : Form {
        List<Clip> clips=new List<Clip>(); ListBox list=new ListBox(); TrackBar timeline=new TrackBar(); PictureBox preview=new PictureBox(); Timer previewTimer=new Timer(); ToolTip tips=new ToolTip();
        TextBox startBox=new TextBox(), endBox=new TextBox(); Label now=new Label(), status=new Label(), ffLabel=new Label(); ProgressBar progress=new ProgressBar();
        Button add=new Button(), cut=new Button(), merge=new Button(), cancel=new Button(); string ffmpeg,ffprobe; Task<string[]> ffmpegInit; readonly Queue<string[]> pendingDrops=new Queue<string[]>(); int selected=-1, dragIndex=-1; bool busy; Point dragOrigin; int previewVersion; const string ClipDragFormat="SkyVideoEditor.ClipIndex";
        public MainForm() {
            Text="SKYVIDEO EDITOR — 修正版 1.7"; AutoScaleMode=AutoScaleMode.Dpi; Font=new Font("Segoe UI",9); ClientSize=new Size(1100,680); MinimumSize=new Size(900,620); StartPosition=FormStartPosition.CenterScreen; BackColor=Color.White;
            ForeColor=Color.FromArgb(31,41,55);BuildUi();ffLabel.Text="● 正在檢查 FFmpeg…";ffLabel.ForeColor=Color.DarkOrange;Shown+=async(s,e)=>await EnsureFfmpegReady();
        }
        void BuildUi() {
            var root=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=3,Margin=Padding.Empty,Padding=Padding.Empty};
            root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));
            root.RowStyles.Add(new RowStyle(SizeType.Absolute,64));root.RowStyles.Add(new RowStyle(SizeType.Percent,100));root.RowStyles.Add(new RowStyle(SizeType.Absolute,38));Controls.Add(root);
            var top=new FlowLayoutPanel{Dock=DockStyle.Top,Height=64,Padding=new Padding(18,11,18,9),BackColor=Color.FromArgb(245,247,250)};
            var title=new Label{Text="SKYVIDEO EDITOR",AutoSize=true,Font=new Font("Segoe UI",19,FontStyle.Bold),ForeColor=Color.FromArgb(17,32,58),Margin=new Padding(0,5,24,0)}; top.Controls.Add(title);
            add.Text="＋ 加入影片"; add.AutoSize=true; add.Click+=(s,e)=>AddFiles(); top.Controls.Add(add);
            var open=new Button{Text="開啟播放器",AutoSize=true}; open.Click+=(s,e)=>OpenPlayer(); top.Controls.Add(open);
            var choose=new Button{Text="FFmpeg 設定",AutoSize=true}; choose.Click+=(s,e)=>ChooseFfmpeg(); top.Controls.Add(choose);
            ffLabel.AutoSize=true; ffLabel.Margin=new Padding(20,8,0,0); top.Controls.Add(ffLabel);top.Dock=DockStyle.Fill;top.Margin=Padding.Empty;top.WrapContents=false;root.Controls.Add(top,0,0);
            var split=new SplitContainer{Dock=DockStyle.Fill,SplitterDistance=520,BackColor=Color.White,Margin=new Padding(12,10,12,8)};root.Controls.Add(split,0,1);
            Load+=(s,e)=>{split.Panel1MinSize=360;split.Panel2MinSize=360;if(split.Width>760)split.SplitterDistance=Math.Max(360,Math.Min(split.Width-360,(int)(split.Width*.48)));};
            var left=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=2,Margin=Padding.Empty};left.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));left.RowStyles.Add(new RowStyle(SizeType.Absolute,44));left.RowStyles.Add(new RowStyle(SizeType.Percent,100)); var bar=new FlowLayoutPanel{Dock=DockStyle.Fill,Height=42,Margin=Padding.Empty,WrapContents=false};
            var up=new Button{Text="↑ 上移",AutoSize=true}; up.Click+=(s,e)=>Reorder(-1); var down=new Button{Text="↓ 下移",AutoSize=true}; down.Click+=(s,e)=>Reorder(1); var rem=new Button{Text="× 移除",AutoSize=true}; rem.Click+=(s,e)=>Remove(-1); bar.Controls.Add(up);bar.Controls.Add(down);bar.Controls.Add(rem);left.Controls.Add(bar);
            list.Dock=DockStyle.Fill; list.IntegralHeight=false;list.BackColor=Color.White; list.ForeColor=Color.FromArgb(31,41,55); list.BorderStyle=BorderStyle.FixedSingle; list.Font=new Font("Segoe UI",10); list.ItemHeight=30; list.AllowDrop=true; list.SelectedIndexChanged+=(s,e)=>SelectClip(list.SelectedIndex); list.MouseDown+=ListMouseDown; list.MouseMove+=ListMouseMove; list.MouseUp+=(s,e)=>dragIndex=-1; list.DragEnter+=ListDragOver; list.DragOver+=ListDragOver; list.DragDrop+=ListDragDrop; left.Controls.Add(list,0,1);split.Panel1.Controls.Add(left);
            var right=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=8,Padding=new Padding(12,8,12,6)}; right.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,92));right.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));
            right.RowStyles.Clear();right.RowStyles.Add(new RowStyle(SizeType.Percent,100));right.RowStyles.Add(new RowStyle(SizeType.Absolute,24));right.RowStyles.Add(new RowStyle(SizeType.Absolute,38));right.RowStyles.Add(new RowStyle(SizeType.Absolute,44));right.RowStyles.Add(new RowStyle(SizeType.Absolute,44));right.RowStyles.Add(new RowStyle(SizeType.Absolute,36));right.RowStyles.Add(new RowStyle(SizeType.Absolute,28));right.RowStyles.Add(new RowStyle(SizeType.Absolute,42));
            preview.Dock=DockStyle.Fill;preview.BackColor=Color.FromArgb(238,242,247);preview.SizeMode=PictureBoxSizeMode.Zoom;preview.BorderStyle=BorderStyle.FixedSingle;right.Controls.Add(preview,0,0);right.SetColumnSpan(preview,2);previewTimer.Interval=260;previewTimer.Tick+=(s,e)=>{previewTimer.Stop();RenderPreview();};
            now.Text="目前 00:00:00.000"; now.AutoSize=true; now.ForeColor=Color.FromArgb(5,150,105); right.Controls.Add(now,0,1);right.SetColumnSpan(now,2);
            timeline.Minimum=0; timeline.Maximum=100000; timeline.TickFrequency=10000; timeline.Dock=DockStyle.Fill; timeline.Scroll+=(s,e)=>TimelineChanged(); right.Controls.Add(timeline,0,2);right.SetColumnSpan(timeline,2);
            right.Controls.Add(new Label{Text="入點 IN",AutoSize=true},0,3);var sb=new Button{Text="設為目前"};sb.Click+=(s,e)=>{startBox.Text=Clip.Fmt(CurrentTime());ApplyTimes();};right.Controls.Add(TimeRow(startBox,sb),1,3);
            right.Controls.Add(new Label{Text="出點 OUT",AutoSize=true},0,4);var eb=new Button{Text="設為目前"};eb.Click+=(s,e)=>{endBox.Text=Clip.Fmt(CurrentTime());ApplyTimes();};right.Controls.Add(TimeRow(endBox,eb),1,4);
            var apply=new Button{Text="套用時間",AutoSize=true};apply.Click+=(s,e)=>ApplyTimes();right.Controls.Add(apply,1,5);
            var fast=new CheckBox{Text="快速無損模式（切點可能靠近關鍵影格）",AutoSize=true,Name="fast"};right.Controls.Add(fast,0,6);right.SetColumnSpan(fast,2);
            var ex=new FlowLayoutPanel{Dock=DockStyle.Fill};cut.Text="分別輸出";cut.AutoSize=true;cut.Click+=(s,e)=>Export(false,fast.Checked);merge.Text="合併輸出";merge.AutoSize=true;merge.Click+=(s,e)=>Export(true,fast.Checked);cancel.Text="取消";cancel.AutoSize=true;cancel.Enabled=false;cancel.Click+=(s,e)=>Cancel();ex.Controls.Add(cut);ex.Controls.Add(merge);ex.Controls.Add(cancel);tips.AutoPopDelay=8000;tips.InitialDelay=300;tips.ReshowDelay=100;tips.SetToolTip(cut,"將清單中的每支影片依入點／出點剪輯，分別儲存成多個 MP4 檔案。");tips.SetToolTip(merge,"將清單中的所有剪輯片段依目前順序合併，儲存成一支 MP4 影片。");right.Controls.Add(ex,0,7);right.SetColumnSpan(ex,2);split.Panel2.Controls.Add(right);
            var bottom=new TableLayoutPanel{Dock=DockStyle.Fill,Margin=Padding.Empty,ColumnCount=2,RowCount=1,Padding=new Padding(18,7,18,7),BackColor=Color.FromArgb(245,247,250)};bottom.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));bottom.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,280));status.Text="就緒";status.Dock=DockStyle.Fill;status.ForeColor=Color.FromArgb(75,85,99);progress.Dock=DockStyle.Fill;progress.Minimum=0;progress.Maximum=100;progress.Value=0;progress.Style=ProgressBarStyle.Continuous;bottom.Controls.Add(status,0,0);bottom.Controls.Add(progress,1,0);root.Controls.Add(bottom,0,2);
            ex.Margin=Padding.Empty;ex.WrapContents=false;
            ApplyTheme(this);
            EnableFileDrop(this);
        }
        static TableLayoutPanel TimeRow(TextBox box,Button button){var row=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=1,Margin=Padding.Empty};row.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));row.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,100));box.Dock=DockStyle.Fill;button.Dock=DockStyle.Fill;row.Controls.Add(box,0,0);row.Controls.Add(button,1,0);return row;}
        async Task EnsureFfmpegReady(){if(ffmpeg!=null)return;if(ffmpegInit==null)ffmpegInit=Task.Run(()=>{string adjacent=System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"ffmpeg.exe");if(File.Exists(adjacent))return new[]{adjacent,FindSibling(adjacent,"ffprobe.exe")};string found=ExtractBundledFfmpeg();if(found==null)found=Find("ffmpeg.exe");return new[]{found,found==null?null:FindSibling(found,"ffprobe.exe")};});string[] result=await ffmpegInit;if(ffmpeg==null){ffmpeg=result[0];ffprobe=result[1];}UpdateFfmpegLabel();}
        void EnableFileDrop(Control c){c.AllowDrop=true;if(c!=list){c.DragEnter+=FileDragOver;c.DragOver+=FileDragOver;c.DragDrop+=(s,e)=>{if(e.Data.GetDataPresent(DataFormats.FileDrop))AddPaths((string[])e.Data.GetData(DataFormats.FileDrop));};}foreach(Control child in c.Controls)EnableFileDrop(child);}
        string ExtractBundledFfmpeg(){try{string dir=System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"SKYVIDEO_EDITOR");string target=System.IO.Path.Combine(dir,"ffmpeg.exe");if(File.Exists(target)&&new FileInfo(target).Length>1000000)return target;using(Stream source=Assembly.GetExecutingAssembly().GetManifestResourceStream("ffmpeg.exe")){if(source==null)return null;Directory.CreateDirectory(dir);using(FileStream output=File.Create(target)){source.CopyTo(output);}return target;}}catch{return null;}}
        void ApplyTheme(Control parent){foreach(Control c in parent.Controls){if(c is Button){var b=(Button)c;b.BackColor=Color.White;b.ForeColor=Color.FromArgb(31,41,55);b.FlatStyle=FlatStyle.Flat;b.FlatAppearance.BorderColor=Color.FromArgb(148,163,184);b.FlatAppearance.MouseOverBackColor=Color.FromArgb(239,246,255);b.Font=new Font("Segoe UI",9,FontStyle.Regular);b.Height=Math.Max(b.Height,34);b.Padding=new Padding(10,3,10,3);}else if(c is TextBox){c.BackColor=Color.White;c.ForeColor=Color.FromArgb(31,41,55);c.Font=new Font("Segoe UI",10);}else if(c is CheckBox){c.ForeColor=Color.FromArgb(31,41,55);}else if(c is Label && c!=now && c!=ffLabel){c.ForeColor=Color.FromArgb(31,41,55);}ApplyTheme(c);}}
        static string FindSibling(string path,string name){string p=System.IO.Path.Combine(System.IO.Path.GetDirectoryName(path),name);return File.Exists(p)?p:null;}
        string Find(string name){var c=new List<string>{System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory,name),System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),"ComfyUI",name),System.IO.Path.Combine("C:\\ComfyUI",name),System.IO.Path.Combine("D:\\ComfyUI",name)};string p=Environment.GetEnvironmentVariable("PATH")??"";c.AddRange(p.Split(';').Select(x=>System.IO.Path.Combine(x,name)));foreach(var x in c)if(File.Exists(x))return x;return null;}
        void UpdateFfmpegLabel(){ffLabel.Text=ffmpeg==null?"● 尚未設定 FFmpeg":"● FFmpeg 已就緒";ffLabel.ForeColor=ffmpeg==null?Color.Salmon:Color.MediumAquamarine;}
        void ChooseFfmpeg(){using(var d=new OpenFileDialog{Filter="ffmpeg.exe|ffmpeg.exe|執行檔|*.exe",Title="選擇 ffmpeg.exe"})if(d.ShowDialog()==DialogResult.OK){ffmpeg=d.FileName;ffprobe=FindSibling(ffmpeg,"ffprobe.exe");UpdateFfmpegLabel();}}
        void AddFiles(){using(var d=new OpenFileDialog{Filter="影片|*.mp4;*.mov;*.mkv;*.webm;*.avi;*.m4v;*.wmv;*.flv;*.mpeg;*.mpg;*.ts;*.mts;*.m2ts|所有檔案|*.*",Multiselect=true,Title="加入影片"})if(d.ShowDialog()==DialogResult.OK)AddPaths(d.FileNames);}
        async void AddPaths(string[] paths){var valid=paths.Where(p=>File.Exists(p)&&Regex.IsMatch(System.IO.Path.GetExtension(p),"^\\.(mp4|mov|mkv|webm|avi|m4v|wmv|flv|mpeg|mpg|ts|mts|m2ts)$",RegexOptions.IgnoreCase)).Distinct(StringComparer.OrdinalIgnoreCase).ToArray();if(valid.Length==0){MessageBox.Show(this,"請拖入支援的影片檔案，例如 MP4、MOV、MKV、WebM、AVI、MPEG 或 TS。","不支援的檔案");return;}if(busy){pendingDrops.Enqueue(valid);status.Text="已保留待處理的 "+valid.Length+" 支影片…";return;}SetBusy(true,"已接收 "+valid.Length+" 支影片，正在準備 FFmpeg…");await EnsureFfmpegReady();if(ffmpeg==null){SetBusy(false,"找不到 FFmpeg");MessageBox.Show(this,"找不到 ffmpeg.exe，請確認它和程式放在同一個資料夾。","FFmpeg 尚未就緒",MessageBoxButtons.OK,MessageBoxIcon.Warning);return;}int added=0;for(int i=0;i<valid.Length;i++){string p=valid[i];SetProgress((int)(i*100.0/valid.Length),"正在讀取第 "+(i+1)+"／"+valid.Length+" 支影片…");try{var c=await Task.Run(()=>Probe(p));clips.Add(c);list.Items.Add(c);added++;}catch(Exception ex){MessageBox.Show(this,p+"\n"+ex.Message,"無法加入影片",MessageBoxButtons.OK,MessageBoxIcon.Warning);}SetProgress((int)((i+1)*100.0/valid.Length),"已處理第 "+(i+1)+"／"+valid.Length+" 支影片");}SetBusy(false,"已加入 "+added+" 支影片");if(selected<0&&clips.Count>0)list.SelectedIndex=0;if(pendingDrops.Count>0){var next=pendingDrops.Dequeue();AddPaths(next);}}
        Clip Probe(string p){if(ffprobe!=null){var r=Run(ffprobe,"-v error -show_entries format=duration:stream=codec_type,width,height,r_frame_rate -of json \""+p+"\"");var m=Regex.Match(r,"\\\"duration\\\"\\s*:\\s*\\\"?([0-9.]+)");if(!m.Success)throw new Exception("無法讀取影片長度");double d=double.Parse(m.Groups[1].Value,CultureInfo.InvariantCulture);return new Clip{Path=p,Name=System.IO.Path.GetFileName(p),Duration=d,Start=0,End=d};}if(ffmpeg==null)throw new Exception("請先在 FFmpeg 設定中選擇 ffmpeg.exe");var text=Run(ffmpeg,"-hide_banner -i \""+p+"\"");var dm=Regex.Match(text,"Duration:\\s*(\\d+):(\\d+):(\\d+(?:\\.\\d+)?)");if(!dm.Success)throw new Exception("無法讀取影片長度");double dur=int.Parse(dm.Groups[1].Value)*3600+int.Parse(dm.Groups[2].Value)*60+double.Parse(dm.Groups[3].Value,CultureInfo.InvariantCulture);return new Clip{Path=p,Name=System.IO.Path.GetFileName(p),Duration=dur,Start=0,End=dur};}
        string Run(string exe,string args){var si=new ProcessStartInfo(exe,args){UseShellExecute=false,RedirectStandardError=true,RedirectStandardOutput=true,CreateNoWindow=true,StandardErrorEncoding=Encoding.UTF8,StandardOutputEncoding=Encoding.UTF8};using(var p=Process.Start(si)){string o=p.StandardOutput.ReadToEnd(),e=p.StandardError.ReadToEnd();p.WaitForExit();return o+"\n"+e;}}
        void SelectClip(int i){previewVersion++;previewTimer.Stop();if(i<0||i>=clips.Count){selected=-1;var previous=preview.Image;preview.Image=null;if(previous!=null)previous.Dispose();return;}selected=i;var oldImage=preview.Image;preview.Image=null;if(oldImage!=null)oldImage.Dispose();var c=clips[i];startBox.Text=Clip.Fmt(c.Start);endBox.Text=Clip.Fmt(c.End);timeline.Value=(int)(c.Start/Math.Max(c.Duration,.001)*100000);now.Text="目前 "+Clip.Fmt(c.Start);previewTimer.Stop();previewTimer.Start();}
        double CurrentTime(){if(selected<0)return 0;return timeline.Value/100000.0*clips[selected].Duration;}
        void TimelineChanged(){if(selected<0)return;previewVersion++;now.Text="目前 "+Clip.Fmt(CurrentTime());previewTimer.Stop();previewTimer.Start();}
        async void RenderPreview(){
            if(selected<0||selected>=clips.Count||ffmpeg==null)return;
            int request=++previewVersion;var clip=clips[selected];string path=clip.Path;
            double at=Math.Min(CurrentTime(),Math.Max(0,clip.Duration-0.1));
            string image=System.IO.Path.Combine(System.IO.Path.GetTempPath(),"skyvideo-preview-"+Guid.NewGuid().ToString("N")+".jpg");
            try{
                await Task.Run(()=>RunChecked(ffmpeg,"-hide_banner -loglevel error -y -ss "+at.ToString("0.###",CultureInfo.InvariantCulture)+" -i \""+path+"\" -frames:v 1 -vf \"scale=720:-2\" \""+image+"\""));
                if(IsDisposed||request!=previewVersion||selected<0||selected>=clips.Count||clips[selected]!=clip)return;
                if(!File.Exists(image))throw new Exception("此時間點沒有可顯示的影格");
                using(var fs=new FileStream(image,FileMode.Open,FileAccess.Read,FileShare.ReadWrite))
                using(var fresh=new Bitmap(fs)){var copy=new Bitmap(fresh);var previous=preview.Image;preview.Image=copy;if(previous!=null)previous.Dispose();}
            }catch(Exception ex){if(!IsDisposed&&request==previewVersion)status.Text="預覽失敗："+ex.Message.Split('\n')[0];}
            finally{try{File.Delete(image);}catch{}}
        }
        void ApplyTimes(){if(selected<0)return;try{var c=clips[selected];double a=Clip.Parse(startBox.Text),b=Clip.Parse(endBox.Text);if(a>=b||b>c.Duration+.05)throw new Exception("入點／出點範圍不正確");c.Start=a;c.End=Math.Min(b,c.Duration);list.Items[selected]=c;timeline.Value=(int)(a/Math.Max(c.Duration,.001)*100000);now.Text="目前 "+Clip.Fmt(a);}catch(Exception ex){MessageBox.Show(this,ex.Message,"時間格式錯誤",MessageBoxButtons.OK,MessageBoxIcon.Warning);}}
        void Reorder(int d){if(selected<0)return;int t=selected+d;if(t<0||t>=clips.Count)return;var c=clips[selected];clips.RemoveAt(selected);clips.Insert(t,c);list.Items.Clear();foreach(var x in clips)list.Items.Add(x);list.SelectedIndex=t;}
        void Remove(int i){if(i<0)i=selected;if(i<0)return;clips.RemoveAt(i);list.Items.RemoveAt(i);if(clips.Count>0)list.SelectedIndex=Math.Min(i,clips.Count-1);else selected=-1;}
        void FileDragOver(object s,DragEventArgs e){e.Effect=!busy&&e.Data.GetDataPresent(DataFormats.FileDrop)?DragDropEffects.Copy:DragDropEffects.None;}
        void ListMouseDown(object s,MouseEventArgs e){dragIndex=-1;if(e.Button!=MouseButtons.Left||busy)return;dragIndex=list.IndexFromPoint(e.Location);dragOrigin=e.Location;if(dragIndex>=0)list.SelectedIndex=dragIndex;}
        void ListMouseMove(object s,MouseEventArgs e){
            if(e.Button!=MouseButtons.Left||dragIndex<0||busy)return;
            Size size=SystemInformation.DragSize;var bounds=new Rectangle(dragOrigin.X-size.Width/2,dragOrigin.Y-size.Height/2,size.Width,size.Height);
            if(bounds.Contains(e.Location))return;
            var data=new DataObject();data.SetData(ClipDragFormat,dragIndex);
            try{list.DoDragDrop(data,DragDropEffects.Move);}finally{dragIndex=-1;}
        }
        void ListDragOver(object s,DragEventArgs e){if(busy){e.Effect=DragDropEffects.None;return;}if(e.Data.GetDataPresent(DataFormats.FileDrop)){e.Effect=DragDropEffects.Copy;return;}e.Effect=e.Data.GetDataPresent(ClipDragFormat)?DragDropEffects.Move:DragDropEffects.None;}
        void ListDragDrop(object s,DragEventArgs e){
            if(busy)return;
            if(e.Data.GetDataPresent(DataFormats.FileDrop)){AddPaths((string[])e.Data.GetData(DataFormats.FileDrop));return;}
            if(!e.Data.GetDataPresent(ClipDragFormat))return;
            int from=(int)e.Data.GetData(ClipDragFormat);if(from<0||from>=clips.Count)return;
            int to=list.IndexFromPoint(list.PointToClient(new Point(e.X,e.Y)));if(to<0)to=clips.Count-1;
            if(to!=from){var clip=clips[from];clips.RemoveAt(from);clips.Insert(to,clip);list.Items.Clear();foreach(var c in clips)list.Items.Add(c);list.SelectedIndex=to;}dragIndex=-1;
        }
        async void Export(bool mergeIt,bool fast){if(busy||clips.Count==0){MessageBox.Show(this,"請先加入影片。","提示");return;}if(ffmpeg==null){ChooseFfmpeg();if(ffmpeg==null)return;}if(!ApplyAndValidate())return;string dest;if(mergeIt){using(var d=new SaveFileDialog{Filter="MP4 影片|*.mp4",DefaultExt="mp4",FileName="merged.mp4"}){if(d.ShowDialog()!=DialogResult.OK)return;dest=d.FileName;}}else{using(var d=new FolderBrowserDialog{Description="選擇片段輸出資料夾"}){if(d.ShowDialog()!=DialogResult.OK)return;dest=d.SelectedPath;}}SetBusy(true,mergeIt?"準備合成…":"準備輸出…");try{var snap=clips.Select(c=>new Clip{Path=c.Path,Name=c.Name,Duration=c.Duration,Start=c.Start,End=c.End,Width=c.Width,Height=c.Height,Fps=c.Fps}).ToList();var output=await Task.Run(()=>DoExport(snap,mergeIt,fast,dest));SetBusy(false,"輸出完成");MessageBox.Show(this,"已建立：\n"+output,"完成",MessageBoxButtons.OK,MessageBoxIcon.Information);}catch(Exception ex){SetBusy(false,"輸出失敗");MessageBox.Show(this,ex.Message,"輸出失敗",MessageBoxButtons.OK,MessageBoxIcon.Error);}}
        bool ApplyAndValidate(){for(int i=0;i<clips.Count;i++){if(i==selected&&!ApplySilent())return false;var c=clips[i];if(c.End<=c.Start)return false;}return true;}
        bool ApplySilent(){try{var c=clips[selected];c.Start=Clip.Parse(startBox.Text);c.End=Clip.Parse(endBox.Text);return c.Start<c.End&&c.End<=c.Duration+.05;}catch{return false;}}
        string DoExport(List<Clip> cs,bool mergeIt,bool fast,string dest){string temp=System.IO.Path.Combine(System.IO.Path.GetTempPath(),"skyvideo-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(temp);try{var parts=new List<string>();double clipSeconds=Math.Max(.001,cs.Sum(c=>c.Length)),totalWork=clipSeconds*(mergeIt?2:1),completed=0;for(int i=0;i<cs.Count;i++){if(busy==false)throw new Exception("已取消");int item=i+1;double itemStart=completed,itemLength=cs[i].Length;SetProgress((int)(itemStart*100/totalWork),"正在處理第 "+item+"／"+cs.Count+" 段…");string outp=mergeIt?System.IO.Path.Combine(temp,"part-"+i.ToString("000")+".mp4"):System.IO.Path.Combine(dest,item.ToString("00")+"_"+System.IO.Path.GetFileNameWithoutExtension(cs[i].Name)+"_cut.mp4");Directory.CreateDirectory(System.IO.Path.GetDirectoryName(outp));string args="-hide_banner -loglevel error -y -progress pipe:1 -nostats -ss "+cs[i].Start.ToString("0.###",CultureInfo.InvariantCulture)+" -i \""+cs[i].Path+"\" -t "+itemLength.ToString("0.###",CultureInfo.InvariantCulture)+" -map 0:v:0 -map 0:a:0? ";args+=fast?"-c copy -avoid_negative_ts make_zero ":"-vf \"scale=trunc(iw/2)*2:trunc(ih/2)*2,format=yuv420p\" -c:v libx264 -preset veryfast -crf 18 -c:a aac -b:a 192k -ar 48000 ";RunCheckedProgress(ffmpeg,args+"-movflags +faststart \""+outp+"\"",itemLength,t=>{int percent=(int)((itemStart+Math.Min(t,itemLength))*100/totalWork);SetProgress(percent,"正在處理第 "+item+"／"+cs.Count+" 段… "+percent+"%");});parts.Add(outp);completed+=itemLength;}if(mergeIt){if(busy==false)throw new Exception("已取消");double mergeStart=completed;SetProgress(50,"正在合成 MP4… 50%");string txt=System.IO.Path.Combine(temp,"concat.txt");File.WriteAllLines(txt,parts.Select(p=>"file '"+p.Replace("'","'\\''")+"'"),new UTF8Encoding(false));RunCheckedProgress(ffmpeg,"-hide_banner -loglevel error -y -progress pipe:1 -nostats -f concat -safe 0 -i \""+txt+"\" -c copy -movflags +faststart \""+dest+"\"",clipSeconds,t=>{int percent=(int)((mergeStart+Math.Min(t,clipSeconds))*100/totalWork);SetProgress(percent,"正在合成 MP4… "+percent+"%");});}SetProgress(100,"處理完成 100%");return mergeIt?dest:string.Join("\n",parts);}finally{try{Directory.Delete(temp,true);}catch{}}}
        void RunChecked(string exe,string args){var si=new ProcessStartInfo(exe,args){UseShellExecute=false,RedirectStandardError=true,RedirectStandardOutput=true,CreateNoWindow=true,StandardErrorEncoding=Encoding.UTF8,StandardOutputEncoding=Encoding.UTF8};using(var p=Process.Start(si)){string o=p.StandardOutput.ReadToEnd(),e=p.StandardError.ReadToEnd();p.WaitForExit();string text=e+"\n"+o;if(p.ExitCode!=0)throw new Exception(text.Length>2500?text.Substring(text.Length-2500):text);}}
        void RunCheckedProgress(string exe,string args,double duration,Action<double> report){var errors=new StringBuilder();var si=new ProcessStartInfo(exe,args){UseShellExecute=false,RedirectStandardError=true,RedirectStandardOutput=true,CreateNoWindow=true,StandardErrorEncoding=Encoding.UTF8,StandardOutputEncoding=Encoding.UTF8};using(var p=new Process{StartInfo=si}){p.ErrorDataReceived+=(s,e)=>{if(e.Data!=null)lock(errors)errors.AppendLine(e.Data);};p.Start();p.BeginErrorReadLine();string line;while((line=p.StandardOutput.ReadLine())!=null){if(!busy){try{p.Kill();}catch{}throw new Exception("已取消");}int eq=line.IndexOf('=');if(eq<1)continue;string key=line.Substring(0,eq),value=line.Substring(eq+1);double seconds;TimeSpan time;if((key=="out_time_us"||key=="out_time_ms")&&double.TryParse(value,NumberStyles.Float,CultureInfo.InvariantCulture,out seconds))report(seconds/1000000.0);else if(key=="out_time"&&TimeSpan.TryParse(value,CultureInfo.InvariantCulture,out time))report(time.TotalSeconds);else if(key=="progress"&&value=="end")report(duration);}p.WaitForExit();if(p.ExitCode!=0){string text;lock(errors)text=errors.ToString();throw new Exception(text.Length>2500?text.Substring(text.Length-2500):text);}}}
        void OpenPlayer(){if(selected<0)return;try{Process.Start(clips[selected].Path);}catch(Exception ex){MessageBox.Show(ex.Message);}}
        void Cancel(){busy=false;cancel.Enabled=false;status.Text="正在取消…";}
        void SetProgress(int value,string text){Action update=()=>{progress.Value=Math.Max(0,Math.Min(100,value));status.Text=text;};if(IsHandleCreated&&InvokeRequired)BeginInvoke(update);else update();}
        void SetBusy(bool b,string text){busy=b;add.Enabled=!b;cut.Enabled=!b;merge.Enabled=!b;cancel.Enabled=b;if(b)progress.Value=0;else if(!text.Contains("完成")&&!text.Contains("已加入"))progress.Value=0;status.Text=text;}
    }
    static class Program { [STAThread] static void Main(){try{Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);Application.Run(new MainForm());}catch(Exception ex){try{File.WriteAllText(System.IO.Path.Combine(System.IO.Path.GetTempPath(),"SKYVIDEO_EDITOR_error.txt"),ex.ToString());}catch{}MessageBox.Show(ex.ToString(),"SKYVIDEO EDITOR 啟動失敗",MessageBoxButtons.OK,MessageBoxIcon.Error);}} }
}
